services:
  admflexnet:
    image: ghcr.io/symrex/docker-adlmflexnetserver:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NLM_URL: ${ADM_FLEXNET_NLM_URL}
    hostname: ${ADM_FLEXNET_HOSTNAME}
    mac_address: ${ADM_FLEXNET_MAC_ADDRESS}
    restart: unless-stopped
    ports:
      - "2080:2080"
      - "27000-27009:27000-27009"
    volumes:
      - ./licenses/latest.lic:/opt/flexnetserver/adsk_server.lic:ro
      - ./logs/:/logs/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - example.env
      - .env
